/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
static yyconst short int yy_acclist[178] =
    {   0,
       43,   43,   46,   45,   45,   45,   45,   26,   45,   27,
       45,   17,   45,   16,   45,   25,   45,   18,   43,   45,
       19,   45,   43,   45,   43,   45,   45,   24,   45,   12,
       45,   45,   11,   45,   41,   45,   41,   45,   41,   45,
       41,   45,   41,   45,   41,   45,   41,   45,   41,   45,
       41,   45,   41,   45,   41,   45,   30,   45,   31,   45,
       41,   45,   41,   45,   41,   45,   28,   45,   29,   45,
       20,   42,   43,   43,   43,   10,   14,   15,   13,   41,
       41,   41,   37,   41,   41,    4,   41,   41,   41,   41,
       41,   33,   41,    3,   41,   41,   41,   21,   41,    8,

       41,   41,   41,   41,   41,   42,   41,   22,   41,   36,
       41,   41,   41,   41,    6,   41,    2,   41,   41,   23,
       41,   41,   41,   41,   41,   44,   44,   44,   42,   44,
       44,   44,   44,   44,   44,   44,    1,   44,   44,   41,
       35,   41,   41,   41,    7,   41,   41,   41,   39,   41,
       41,   44,   44,   44,   44,   44,   44,   41,   34,   41,
       41,   32,   41,   41,   41,   41,   41,   41,   40,   41,
        9,   41,   41,   38,   41,    5,   41
    } ;

static yyconst short int yy_accept[148] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,   10,   12,
       14,   16,   18,   21,   23,   25,   27,   28,   30,   32,
       33,   35,   37,   39,   41,   43,   45,   47,   49,   51,
       53,   55,   57,   59,   61,   63,   65,   67,   69,   71,
       71,   71,   72,   72,   72,   73,   73,   73,   73,   73,
       74,   75,   75,   76,   77,   78,   79,   80,   81,   82,
       83,   85,   86,   88,   89,   90,   91,   92,   94,   96,
       97,   98,  100,  102,  103,  104,  105,  106,  106,  106,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      108,  110,  112,  113,  114,  115,  117,  119,  120,  122,

      123,  124,  125,  126,  127,  128,  129,  131,  132,  133,
      134,  135,  136,  137,  138,  139,  140,  141,  143,  144,
      145,  147,  148,  149,  151,  152,  153,  154,  155,  156,
      157,  158,  159,  161,  162,  164,  165,  166,  167,  168,
      169,  171,  173,  174,  176,  178,  178
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    1,    1,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   21,   21,   28,   29,   30,   31,   32,
       21,   33,   34,   35,   21,   21,   36,   37,   38,   21,
       39,    1,   40,    1,    1,    1,   41,   21,   21,   21,

       42,   21,   43,   21,   44,   21,   21,   45,   21,   46,
       21,   21,   21,   47,   48,   49,   21,   21,   21,   21,
       21,   21,   50,    1,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    3,    3,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1
    } ;

static yyconst short int yy_base[157] =
    {   0,
        0,    0,  420,   39,  446,   41,   54,   47,   49,   56,
       58,   60,   62,   70,   65,   67,   72,   74,   78,   84,
       86,  104,  126,  131,  129,  136,  141,  144,  146,  149,
      154,  160,  159,  178,  159,  165,  166,  184,  188,  406,
      195,  405,  199,  177,  404,  207,  210,  209,  214,  218,
      222,  215,  227,  403,  402,  401,  400,  223,  399,   84,
      398,  208,  396,   55,  232,  219,  233,  395,  394,  234,
      237,  392,  391,  240,  244,  245,  247,    0,  389,  446,
      257,  256,  262,  259,  272,  264,  392,  272,  390,  385,
      381,  380,   71,  193,  254,  379,  378,  269,  377,  277,

      258,  271,  251,  278,  293,  304,  296,  307,  311,  324,
      316,  320,  328,  380,  339,  342,  308,  375,  321,  332,
      374,  312,  329,  373,  302,  346,  348,  353,  361,  357,
      366,  358,  303,  276,  278,  352,  365,  366,  370,  371,
      274,  176,  372,   90,   53,  446,  418,  421,  424,  427,
      430,   54,  433,  436,  439,  442
    } ;

static yyconst short int yy_def[157] =
    {   0,
      146,    1,  146,  147,  146,  147,  148,  147,  147,  147,
      147,  147,  149,  147,  147,  149,  147,  147,  147,  147,
      147,  146,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,  147,  147,   22,   22,   22,  147,  147,  146,
      147,  146,  150,  150,  146,  150,  148,  150,  147,  147,
      149,  151,  147,  146,  146,  146,  146,   22,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  153,  153,  146,
      154,  150,  154,  150,  154,  155,  151,  151,  156,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,

      152,  152,  152,  146,  153,  150,  146,  150,  150,  154,
      146,  153,  147,  151,  151,  151,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  146,  146,  150,  150,  147,
      151,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,    0,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146
    } ;

static yyconst short int yy_nxt[498] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
        4,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   23,   28,   23,   23,   29,
       30,   23,   23,   23,   31,   32,   23,   23,   33,   34,
       23,   23,   23,   35,   23,   23,   36,   37,   23,   38,
       39,   41,   41,   41,   41,   44,   90,   45,   42,   41,
       41,   41,   41,  146,   46,   78,   47,   47,   41,   41,
       41,   41,   41,   41,   50,   51,   52,   53,   53,   50,
       50,  146,   41,   41,   41,   41,   41,   41,   94,   54,
       41,   41,   46,   48,   78,   55,   41,   41,   41,   41,

      146,   56,  117,   57,   40,   91,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   58,   58,   40,   40,
       40,   40,   40,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   60,   59,   59,   59,   61,   59,   59,
       59,   59,   40,   40,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   40,   40,   59,   64,   62,   65,   59,
       59,   63,   59,   67,   59,   59,   66,   68,   70,   59,
       59,   41,   41,   69,   59,   59,   71,   59,   59,   59,
       80,   72,   59,   59,   73,   74,  146,   59,   59,   59,
       41,   41,   59,   59,   59,   59,   41,   41,   59,   59,

       41,   41,   80,  146,   75,   79,   76,   41,   41,   81,
       80,   44,   80,   45,   77,  118,   82,   83,   78,   81,
       85,   88,   47,   47,   79,   89,   41,   41,   79,   78,
       53,   53,   86,   79,   50,   50,   92,   79,   82,   53,
       53,   93,   78,   78,   78,   84,   82,   78,   82,   48,
       78,   96,   59,   95,   78,   78,   59,   78,   44,   80,
      107,  146,   80,   44,  146,  107,  100,   97,  146,   84,
       98,   99,  109,   44,  112,  107,  113,  113,   88,  146,
      119,  146,  110,  114,  146,  102,  146,  146,  146,  120,
      126,  126,  101,  103,  125,   82,  108,   84,   82,  123,

      109,  108,  139,  121,  122,  127,  127,   80,  126,  126,
       80,  108,  146,  146,   80,  124,  128,  128,  146,  128,
      128,   84,  146,  128,  128,   44,   78,  107,  126,  126,
      105,  146,  127,  127,  135,  132,  129,  129,   79,  146,
      130,  130,  146,   82,  133,   88,   82,  137,   88,   84,
       82,  131,  131,  114,  131,  131,   80,  134,  126,  126,
      126,  126,  146,  108,   80,  128,  128,   79,  146,  130,
      130,  136,   88,  128,  128,  146,  146,  138,  131,  131,
      146,  146,  146,  146,  146,  146,   88,  146,  146,  146,
      146,  146,   82,  140,  145,  146,  116,  143,   88,  105,

       82,   78,   78,  142,   78,   78,   78,  141,   78,   78,
       78,   78,   78,   78,   78,   78,   78,  144,   40,  146,
       40,   43,   43,   43,   49,  146,   49,   44,   44,   44,
       87,  146,   87,  104,  146,  104,  106,  106,  106,  111,
      146,  111,  115,  146,  115,    3,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146

    } ;

static yyconst short int yy_chk[498] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    4,    6,    6,    7,  152,    7,    6,    8,
        8,    9,    9,  145,    7,   64,    7,    7,   10,   10,
       11,   11,   12,   12,   13,   13,   14,   15,   15,   16,
       16,   93,   14,   14,   17,   17,   18,   18,   64,   17,
       19,   19,    7,    7,   60,   19,   20,   20,   21,   21,

      144,   20,   93,   21,   22,   60,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   23,   25,   24,   25,   23,
       24,   24,   25,   27,   24,   26,   26,   28,   29,   26,
       27,   33,   33,   28,   27,   29,   29,   28,   30,   29,
       44,   30,   30,   31,   31,   32,  142,   31,   35,   32,
       34,   34,   35,   32,   36,   37,   38,   38,   36,   37,

       39,   39,   43,   94,   35,   41,   36,   41,   41,   43,
       46,   47,   48,   47,   37,   94,   44,   46,   62,   48,
       47,   52,   47,   47,   49,   52,   49,   49,   50,   66,
       50,   50,   51,   58,   51,   51,   62,   53,   43,   53,
       53,   62,   65,   67,   70,   46,   46,   71,   48,   47,
       74,   66,   58,   65,   75,   76,   58,   77,   81,   82,
       81,  103,   84,   83,   95,   83,   74,   67,  101,   84,
       70,   71,   83,   85,   86,   85,   86,   86,   88,   98,
       95,  102,   85,   88,  141,   76,  134,  100,  135,   95,
      104,  104,   75,   77,  103,   82,   81,   84,   84,  101,

       83,   83,  134,   98,  100,  105,  105,  106,  107,  107,
      108,   85,  125,  133,  109,  102,  106,  106,  117,  108,
      108,  109,  122,  109,  109,  110,  111,  110,  111,  111,
      112,  119,  112,  112,  122,  117,  110,  110,  113,  123,
      113,  113,  120,  106,  119,  115,  108,  125,  116,  109,
      109,  115,  115,  116,  116,  116,  128,  120,  126,  126,
      127,  127,  136,  110,  129,  128,  128,  130,  132,  130,
      130,  123,  131,  129,  129,  137,  138,  132,  131,  131,
      139,  140,  143,  124,  121,  118,  114,   99,   97,   96,
       92,   91,  128,  136,  143,   90,   89,  139,   87,   79,

      129,   73,   72,  138,   69,   68,   63,  137,   61,   59,
       57,   56,   55,   54,   45,   42,   40,  140,  147,    3,
      147,  148,  148,  148,  149,    0,  149,  150,  150,  150,
      151,    0,  151,  153,    0,  153,  154,  154,  154,  155,
        0,  155,  156,    0,  156,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexico.l"
#define INITIAL 0
#line 2 "Lexico.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"
#include "Simbolos.h"

#define MIN_INT -32768
#define MAX_INT 32767
#define MAX_LEN_STRING 30
#define MIN_FLOAT -100000
#define MAX_FLOAT 100000

FILE *yyin;

void procesarID();
void procesarInt();
void procesarFloat();
void procesarString();
void procesarTipoVariable();
int existeID(char* yytext);
char nombreSimbolo[50];

#line 580 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 89 "Lexico.l"


#line 734 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 147 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 446 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 91 "Lexico.l"
{printf("\nCOMMENT: %s", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 93 "Lexico.l"
{printf("\nGET: %s", yytext); return GET;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "Lexico.l"
{printf("\nIN: %s", yytext); return IN;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 95 "Lexico.l"
{printf("\nDO: %s", yytext); return DO;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "Lexico.l"
{printf("\nENDWHILE: %s", yytext); return ENDWHILE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "Lexico.l"
{printf("\nFOR: %s", yytext); return FOR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 98 "Lexico.l"
{printf("\nNEXT: %s", yytext); return NEXT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 99 "Lexico.l"
{printf("\nTO: %s", yytext); return TO;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 100 "Lexico.l"
{printf("\nDISPLAY: %s", yytext); return DISPLAY;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "Lexico.l"
{printf("\nOP_ASIG: %s", yytext); return OP_ASIG;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "Lexico.l"
{printf("\nOP_GT: %s", yytext); return OP_GT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "Lexico.l"
{printf("\nOP_LT: %s", yytext); return OP_LT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "Lexico.l"
{printf("\nOP_GE: %s", yytext); return OP_GE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "Lexico.l"
{printf("\nOP_LE: %s", yytext); return OP_LE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "Lexico.l"
{printf("\nOP_EQ: %s", yytext); return OP_EQ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "Lexico.l"
{printf("\nOP_SUM: %s", yytext); return OP_SUM;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "Lexico.l"
{printf("\nOP_MULT: %s", yytext); return OP_MULT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "Lexico.l"
{printf("\nOP_MEN: %s", yytext); return OP_MEN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 110 "Lexico.l"
{printf("\nOP_DIV: %s", yytext); return OP_DIV;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 111 "Lexico.l"
{printf("\nOP_DIST: %s", yytext); return OP_DIST;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 112 "Lexico.l"
{printf("\nOP_OR: %s", yytext); return OP_OR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "Lexico.l"
{printf("\nOP_AND: %s", yytext); return OP_AND;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "Lexico.l"
{printf("\nNOT: %s", yytext); return NOT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "Lexico.l"
{printf("\nOP_ENDLINE: %s", yytext); return OP_ENDLINE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "Lexico.l"
{printf("\nOP_COMA: %s", yytext); return OP_COMA;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "Lexico.l"
{printf("\nOP_PAR: %s", yytext); return OP_PAR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 118 "Lexico.l"
{printf("\nCL_PAR: %s", yytext); return CL_PAR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "Lexico.l"
{printf("\nOP_KEY: %s", yytext); return OP_KEY;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 120 "Lexico.l"
{printf("\nCL_KEY: %s", yytext); return CL_KEY;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 121 "Lexico.l"
{printf("\nOP_CORC: %s", yytext); return OP_CORC;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 122 "Lexico.l"
{printf("\nCL_COR: %s", yytext); return CL_COR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 123 "Lexico.l"
{printf("\nWHILE: %s", yytext); return WHILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 124 "Lexico.l"
{printf("\nIF: %s", yytext); return IF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 125 "Lexico.l"
{printf("\nENDIF: %s", yytext); return ENDIF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 126 "Lexico.l"
{printf("\nELSE: %s", yytext); return ELSE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 127 "Lexico.l"
{printf("\nDIM: %s", yytext); return DIM;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 128 "Lexico.l"
{printf("\nAS: %s", yytext); return AS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 129 "Lexico.l"
{printf("\nINT_TYPE: %s", yytext); procesarTipoVariable(); return INT_TYPE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 130 "Lexico.l"
{printf("\nREAL_TYPE: %s", yytext); procesarTipoVariable(); return REAL_TYPE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "Lexico.l"
{printf("\nSTRING_TYPE: %s", yytext); procesarTipoVariable(); return STRING_TYPE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 133 "Lexico.l"
{procesarID(); return ID;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 134 "Lexico.l"
{procesarString(); return STRING_DEC;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 135 "Lexico.l"
{procesarInt(); return INT_NUM;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 136 "Lexico.l"
{procesarFloat(); return FLOAT_NUM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 138 "Lexico.l"
ECHO;
	YY_BREAK
#line 1050 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 147 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 147 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 146);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 138 "Lexico.l"



// int main(int argc,char *argv[])
// {
//     if ((yyin = fopen(argv[1], "rt")) == NULL)
//     {
//         printf("No se puede abrir el archivo: %s n", argv[1]);
//     }
//     else
//     {
//         yylex();
//     }
//     fclose(yyin);

// }
// int yylex (void)
// {
//     estado = 0
// }
// int yyerror(void)
// {
//     printf("Error léxico: Caracter inválido: %s\n", yytext);
//     exit (1);
// }

void procesarID(){
    yylval.str_val = strdup(yytext);
    printf("\nID: %s", yytext);
    if(existeID(yytext) == 0)
        agregarVariable(yytext);
}

void procesarInt(){
    int num_int = atoi(yytext);
    yylval.str_val = yytext;
    if(num_int > MAX_INT || num_int < MIN_INT){
        printf("\nError, el numero %s excede el rango entero", yytext);
        exit(-1);
    }else{
        printf("\nINT_NUM: %s", yytext);
        strcpy(nombreSimbolo, "_");
        strcat(nombreSimbolo,yytext);
        printf("Constante a escribir: %s", nombreSimbolo);
        agregarSimbolo(nombreSimbolo, "CTE_INTEGER", yytext, strlen(yytext), "INT_NUM");
    }
}

void procesarFloat(){
    int num_float = atof(yytext);
    yylval.str_val = yytext;
    if(num_float > MAX_FLOAT || num_float < MIN_FLOAT){
        printf("\nError, el numero %s excede el rango float", yytext);
        exit(-1);
    }else{
        printf("\nFLOAT_NUM: %s", yytext);
        strcpy(nombreSimbolo, "_");
        strcat(nombreSimbolo,yytext);
        agregarSimbolo(nombreSimbolo, "CTE_FLOAT", yytext, strlen(yytext), "FLOAT_NUM");
    }
}

void procesarString(){
    int long_string = strlen(yytext);
    yylval.str_val = strdup(yytext);
    if(long_string > MAX_LEN_STRING){
        printf("\nError, el string %s excede el tamanio maximo de %d caracteres", yytext, MAX_LEN_STRING);
        exit(-1);
    }else{
        printf("\nSTRING_DEC: %s", yytext);
        strcpy(nombreSimbolo, "_");
        strcat(nombreSimbolo,yytext);
        agregarSimbolo(nombreSimbolo, "CTE_STRING", yytext, strlen(yytext), "STRING_DEC");
    }
}

void procesarTipoVariable(){
    char nombreID[50];
    getNextNombreID(nombreID);
    agregarSimbolo(nombreID, yytext, "", 0, "ID");
}

int existeID(char* yytext){
    for(int i = 0; i < getCantSimbolos(); i++){
        if(strcmp(simbolos[i].nombre, yytext) == 0)
            return 1;
    }
    return 0;
}